name: My Workflow

on:
  workflow_dispatch

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: '5'
      - name: Revert PR
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git revert -m 1 HEAD
          git push 
