name: My Workflow

on:
  workflow_dispatch

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '5'
      - run: git revert HEAD~1
      - name: Request approval
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Deploy to ${{ matrix.environment }}: Approval required"
          labels: "approval required, ${{ matrix.environment }}"
          body: |
            @${{ github.actor }} Please review and approve this deployment to ${matrix.environment}.
          reviewers: ${{ secrets.REVIEWERS }}
