name: My Workflow

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to production'

jobs:






  approve:
    runs-on: ubuntu-latest

    if: github.event.inputs.deploy == 'true'
    steps:
      - name: Request approval
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Deploy to ${{ matrix.environment }}: Approval required"
          labels: "approval required, ${{ matrix.environment }}"
          body: |
            @${{ github.actor }} Please review and approve this deployment to ${matrix.environment}.
          reviewers: ${{ secrets.REVIEWERS }}
