name: My Workflow

on: [push]

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 5
      - run: git revert HEAD~1 


