name: My Workflow

on:
  workflow_dispatch

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '5'
      - name: Rollback on failure
        run: |
          git revert -m 1 --no-edit HEAD~1
          git push
